
title: Squad GR
tagline: Ο πρώτος Ελληνικός Server στο Squad
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Ο πρώτος Ελληνικός server για Squad
baseurl: "/joinsquad-gr" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
static: "/static"
twitter_username: jekyllrb
github_username:  hellenic-milsim


# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - .idea
 - workspace.iml
 - readme.md
